#!/bin/bash
#must be use as root
# cd /home/ese/leprechuan.net/freeshell/debian;cd ..;rm -rf freeshell; git clone https://github.com/leprechuanese/freeshell.git; cd freeshell/debian; sudo ./install-debian

#  2184  git add *
# 2185  git commit -m "some changes"
# 2186  git config --global user.email "leprechuanese@gmail.com"
# 2187  git config --global user.name "ese"
# 2188  git commit -m "some changes"
# 2189  git push origin master

echo "
`basename $0` Version 0.01

This script will make your debian box to accept ssh
in the for:
ssh -l new server.tdl
passwd: new

To login into the box, create a new user and setup permits
and webspace, use with caution!

"


if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

#please modify if you want any different
theuser="new"
password="new"

mv bin/freeshell /bin/freeshell
echo "/bin/freeshell" >> /etc/shells
chmod +x  /bin/freeshell
groupadd freeshell

#array=( zero one two three four five )
pkg=(whois sudo irssi eggdrop supybot curl znc openssh-server)

#check if $pkg is installed if not install
#if dpkg --get-selections | grep -q "^$pkg[[:space:]]*install$" >/dev/null; then 
#	echo "Already installed: $pkg"
#fi

apt-get -y update
apt-get -y upgrade

for i in $pkg; do
   apt-get -y install "$i"
done;

#apt-get -y install openssh-server
#apt-get -y install curl
#apt-get -y install znc
#apt-get -y install sudo
#apt-get -y install irssi
#apt-get -y install eggdrop
#apt-get -y install supybot
#apt-get -y install whois

thepass=$(mkpasswd $password)

useradd -m -g freeshell -s /bin/freeshell -p "$thepass" "$theuser"
sudo mkdir -p "/home/$theuser/public_html"
sudo chmod 710 "/home/$theuser"



cp etc/sudoers.d/* /etc/sudoers.d/.
mv /etc/sudoers /etc/sudoers.old
cp etc/sudoers /etc/sudoers


mv /etc/adduser.conf /etc/adduser.conf.old
cp etc/adduser.conf /etc/adduser.conf

usermod -G root,freeshell,sudo new

#a2enmod userdir
#service apache2 restart

#mv /etc/security/limits.conf /etc/security/limits.conf-old

#sysctl kernel.randomize_va_space=2
#sysctl net.ipv4.icmp_echo_ignore_broadcasts=1
#sysctl net.ipv4.icmp_ignore_bogus_error_responses=1
#sysctl net.ipv4.conf.all.accept_redirects=0
#sysctl net.ipv4.conf.default.accept_redirects=0
#sysctl net.ipv4.conf.all.accept_source_route=0
#sysctl net.ipv4.conf.default.accept_source_route=0
#sysctl net.ipv4.ip_forward=0
#sysctl kernel.sysrq=0
#sysctl net.ipv4.tcp_syncookies=1
#sysctl net.ipv4.conf.all.rp_filter=1
#sysctl net.ipv4.conf.all.log_martians=1
 
#mv /etc/ssh/sshd_config /etc/ssh/sshd_config-old
#cp etc/ssh/sshd_config etc/ssh/sshd_config

#chmod 750 `which ping`
#chmod 750 `which yes`
#chmod 750 `which netstat`

