#!/bin/bash
#must be use as root
#

echo "
`basename $0` Version 0.01

This script will make your debian box to accept ssh
in the for:
ssh -l new server.tdl
passwd: new

To login into the box, create a new user and setup permits
and webspace, use with caution!

"


if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

#please modify if you want any different
theuser="new"
password="new"

mv bin/freeshell /bin/freeshell
echo "/bin/freeshell" >> /etc/shells
chmod +x  /bin/freeshell

useradd new -g freeshell -s /bin/freeshell -p `mkpasswd $password` $theuser

pkg="sudo curl irssi eggdrop supybot"

#check if $pkg is installed if not install
if dpkg --get-selections | grep -q "^$pkg[[:space:]]*install$" >/dev/null; then 
	echo "Already instaled: $pkg"
else
	apt-get install "$pkg"
fi

mkdir -p /etc/sodoers.d
cp etc/sudoers.d/* /etc/sudoers.d/.
mv /etc/sudoers /etc/sudoers.old
cp etc/sudoers /etc/sudoers

chmod 0440 /etc/sudoers.d/freeshell
chmod 0440 /etc/sudoers

mv /etc/adduser.conf /etc/adduser.conf.old
cp etc/adduser.conf /etc/adduser.conf

usermod -G root,freeshell,sudo new

apt-get update
apt-get upgrade

aptitude install apache2 openssh-server harden fail2ban libpam-chroot
a2enmod userdir
service apache2 restart

mv /etc/security/limits.conf /etc/security/limits.conf-old
c
sysctl kernel.randomize_va_space=2
sysctl net.ipv4.icmp_echo_ignore_broadcasts=1
sysctl net.ipv4.icmp_ignore_bogus_error_responses=1
sysctl net.ipv4.conf.all.accept_redirects=0
sysctl net.ipv4.conf.default.accept_redirects=0
sysctl net.ipv4.conf.all.accept_source_route=0
sysctl net.ipv4.conf.default.accept_source_route=0
sysctl net.ipv4.ip_forward=0
sysctl kernel.sysrq=0
sysctl net.ipv4.tcp_syncookies=1
sysctl net.ipv4.conf.all.rp_filter=1
sysctl net.ipv4.conf.all.log_martians=1
 
mv /etc/ssh/sshd_config /etc/ssh/sshd_config-old
cp etc/ssh/sshd_config etc/ssh/sshd_config

chmod 750 `which ping`
chmod 750 `which yes`
chmod 750 `which netstat`
#chmod 4750 `which sudo`

history | cut -c 8- | curl -F 'sprunge=<-' http://sprunge.us > success

